class Menu

  class << self

    def parents
      {
        # API
        "document_database"                 => "java_api",
        "object_database"                   => "java_api",
        "object2_record_java_binding"       => "object_database",
        "graph_database"                    => "java_api",
        "graph_database_raw"                => "graph_database",
        "graph_database_native"             => "graph_database",
        "graph_database_tinkerpop"          => "graph_database",
        "graph_ed_tutorial"                 => "graph_database",
        "java_web_apps"                     => "java_api",
        "server_management_java"            => "java_api",
        "java_multi_threading"              => "java_api",
        "fetching_strategies"               => "java_api",
        "schema"                            => "java_api",
        "hook"                              => "java_api",
        "embedded_server"                   => "java_api",
        "troubleshooting_java"              => "java_api",
        # SQL
        "sql_alter_class"                   => "sql",
        "sql_alter_cluster"                 => "sql",
        "sql_alter_database"                => "sql",
        "sql_alter_property"                => "sql",
        "sql_create_class"                  => "sql",
        "sql_create_index"                  => "sql",
        "sql_create_link"                   => "sql",
        "sql_create_property"               => "sql",
        "sql_delete"                        => "sql",
        "sql_find_references"               => "sql",
        "sql_grant"                         => "sql",
        "sql_insert"                        => "sql",
        "sql_query"                         => "sql",
        "sql_rebuild_index"                 => "sql",
        "sql_remove_class"                  => "sql",
        "sql_remove_index"                  => "sql",
        "sql_remove_property"               => "sql",
        "sql_revoke"                        => "sql",
        "sql_syntax"                        => "sql",
        "sql_truncate_class"                => "sql",
        "sql_truncate_cluster"              => "sql",
        "sql_truncate_record"               => "sql",
        "sql_update"                        => "sql",
        "sql_where"                         => "sql",
        # DB Server
        "automatic_backup"                  => "db_server",
        "orient_db_rest"                    => "db_server",
        "network_binary_protocol"           => "db_server",
        "wrapping_as_a_windows_service"     => "db_server",
        # Console
        "console_command_browse_class"      => "console_commands",
        "console_command_browse_cluster"    => "console_commands",
        "console_command_classes"           => "console_commands",
        "console_command_clusters"          => "console_commands",
        "console_command_config"            => "console_commands",
        "console_command_config_get"        => "console_commands",
        "console_command_config_set"        => "console_commands",
        "console_command_connect"           => "console_commands",
        "console_command_create_cluster"    => "console_commands",
        "console_command_create_db"         => "console_commands",
        "console_command_declare_intent"    => "console_commands",
        "console_command_dictionary_get"    => "console_commands",
        "console_command_dictionary_keys"   => "console_commands",
        "console_command_dictionary_put"    => "console_commands",
        "console_command_dictionary_remove" => "console_commands",
        "console_command_disconnect"        => "console_commands",
        "console_command_display_record"    => "console_commands",
        "console_command_drop_cluster"      => "console_commands",
        "console_command_drop_db"           => "console_commands",
        "console_command_export"            => "console_commands",
        "console_command_export_record"     => "console_commands",
        "console_command_get"               => "console_commands",
        "console_command_import"            => "console_commands",
        "console_command_info"              => "console_commands",
        "console_command_info_class"        => "console_commands",
        "console_command_load_record"       => "console_commands",
        "console_command_profiler"          => "console_commands",
        "console_command_properties"        => "console_commands",
        "console_command_reload_record"     => "console_commands",
        "console_command_set"               => "console_commands",
        "console_command_share_database"    => "console_commands",
        "console_command_update"            => "console_commands",
      }
    end
  end


end